class IssueCategories {
  static const categoriesMap = {
    'Ampel, Verkehrszeichen': [
      'Ampel komplett ausgefallen',
      'einzelnes Signal am Mast ausgefallen',
      'einzelnes Signal über der Fahrbahn ausgefallen',
      'überflüssiges Verkehrsschild',
      'Ampel durch Pflanze verdeckt',
      'Verkehrsschild verdeckt / beschädigt entwendet',
    ],
    'Beleuchtung': [
      'Leuchte an Straße, Geh- oder Radweg defekt',
      'Leuchtenmast beschädigt',
      'Leuchtenglas/-wanne beschädigt',
    ],
    'Bushaltestelle': [
      'Glasbruch Wartehalle',
      'Glasbruch Vitrine',
      'Deckenbeleuchtung defekt',
      'Vitrinenbeleuchtung defekt',
      'Bank verschmutzt',
      'Graffiti',
      'Wartehalle verschmutzt',
      'Fahrplan fehlt',
    ],
    'Geh-/Radweg, Radverkehr': [
      'lose Gehwegplatten/Pflastersteine',
      'Behinderung durch Pflanzen',
      'starke Verschmutzung/Scherben',
      '"Schrottfahrrad"',
      'Behinderung durch Sperrpfosten/Umlaufsperren',
      'Sperrpfosten/Umlaufsperre fehlt',
      'Fahrradbox: Tür defekt',
      'Fahrradbox vermüllt',
    ],
    'Radwegweisung': [
      'Pfosten schief, verdreht, umgefallen',
      'Radwegweiser fehlt, Befestigung defekt',
      'Radwegweiser unkenntlich (verdreckt, beschmiert, verklebt, verblasst, zugewachsen)',
    ],
    'Grünanlage, Spielplatz': [
      'Spielgerät beschädigt',
      'Bank beschädigt',
      'Pflanzung/Bäume beschädigt',
      'starke Verschmutzung/Scherben',
      '"wilde" Müllablagerung',
    ],
    'Eichenprozessionsspinner': [
      'Eichenprozessionsspinner an öffentlichen Kindergärten / öffentlichen Schulen',
      'Eichenprozessionsspinner an öffentlichen Spielplätzen, Sport-/Freizeitanlagen',
      'Eichenprozessionsspinner an Krankenhäusern / anderen öffentlichen Einrichtungen',
      'Eichenprozessionsspinner an Bushaltestellen',
      'Eichenprozessionsspinner an Bäumen zwischen der Bebauung',
      'Eichenprozessionsspinner an Straßenbäumen',
      'Eichenprozessionsspinner an Bäumen an städtischen Waldwegen',
    ],
    'Straße': [
      'Schlagloch',
      'Behinderung durch Pflanzen',
      'stark verschmutzte Fahrbahn',
      'Überflutung, Straßenablauf verstopft',
      'Unebenheiten durch Kanaldeckel',
      'stark schadhafte Fahrbahnmarkierung',
    ],
    'Brücken': [
      'Schaden am Brückenbelag',
      'Schaden am Brückenbelag',
      'Graffitis',
      'Brückenabläufe verstopft',
      'lose Teile (Steine, Abdeckungen)',
    ],
    'Gewässer': [
      'Abflusshindernis/Rückstau',
      'Müll, "Schrottfahrrad"',
      'Nagetierbefall',
    ],
    'Kanalisation': [
      'Kanaldeckel fehlt / defekt',
      'Rattenbefall',
      'Verstopfung/Rückstau',
      'Geruchsbelästigung',
    ],
  };
}